### ISSUE TITLE
For LLM

### ISSUE THREAD

**Issue by mumuyeye** [abdouaziz/SBert#1]
Could you please tell me whether your code can apply in LLM,such as GPT-J? I sincerely hope you can answer my question!

**Comment by abdouaziz** [comment]
Hello @mumuyeye  ,  unfortunately, no. The code that I shared is about semantic similarity, given two sentences; it tells if they are semantically similar or not. 

In your case, please try the links below, and I hope they will be helpful:

- GPTJ Hugging Face Transformers Documentation :  https://huggingface.co/docs/transformers/model_doc/gptj
- EleutherAI GPT-J-6B Model : https://huggingface.co/EleutherAI/gpt-j-6b
